/**
 * Wiki import format — parse exported wiki pages back into memory payloads.
 *
 * Counterpart of handlers/wiki-export.ts renderPage(). Kept pure (no fs, no
 * config) so the parse rules can be property-tested against the exporter's
 * byte format: front-matter keys, an H1 title, free-form content, and an
 * optional "## 关联" wikilink section that must NOT become part of the saved
 * content (edges are not restorable through the current API).
 */

export const WIKI_GENERATOR_MARKER = "generator: oh-memos-wiki-export";

export interface ParsedWikiPage {
  id: string;
  /** Uppercase MCP business type, e.g. BUGFIX. */
  type: string;
  /** Lifecycle status from front-matter; importers skip non-activated pages. */
  status: string;
  tags: string[];
  confidence?: number;
  created?: string;
  updated?: string;
  title: string;
  /** Body without the [TYPE] prefix and without the 关联 section. */
  content: string;
  /** Raw wikilink lines from the 关联 section (reporting only). */
  related: string[];
}

export type ParseWikiResult =
  | { ok: true; page: ParsedWikiPage }
  /**
   * `foreign` separates "this file was never ours" (a hand-written note or
   * another tool's output — normal, leave it alone) from "our page, but
   * malformed" (a real failure worth reporting). The importer must not have to
   * match on `reason` text to tell them apart.
   */
  | { ok: false; reason: string; foreign: boolean };

/**
 * Must satisfy the server's typed fast path (core.py MOS_TYPED_SAVE_FAST
 * stores verbatim when content matches ^\[([A-Z_]{3,24})\]\s). One char
 * stricter on the first letter so types always read as MCP business types.
 */
const TYPE_RE = /^[A-Z][A-Z_]{2,23}$/;

const RELATED_HEADING = "## 关联";

/** Strip a leading `[TYPE] ` prefix — mirrors the exporter's strip on write. */
export function stripTypePrefix(text: string): string {
  return text.replace(/^\[[A-Z_]+\]\s*/, "");
}

/** Rebuild the exact memory_content string a page stands for. */
export function buildMemoryContent(page: ParsedWikiPage): string {
  return `[${page.type}] ${page.content}`;
}

function parseTags(raw: string): string[] {
  if (!raw.startsWith("[")) return [];
  try {
    const value = JSON.parse(raw);
    return Array.isArray(value) ? value.map(String) : [];
  } catch {
    return [];
  }
}

export function parseWikiPage(raw: string): ParseWikiResult {
  const lines = raw.replace(/\r\n?/g, "\n").split("\n");
  if (lines[0]?.trim() !== "---") {
    return { ok: false, reason: "missing front-matter", foreign: true };
  }

  const end = lines.indexOf("---", 1);
  if (end === -1) return { ok: false, reason: "unterminated front-matter", foreign: true };

  const fields = new Map<string, string>();
  for (const line of lines.slice(1, end)) {
    const idx = line.indexOf(":");
    if (idx <= 0) continue;
    fields.set(line.slice(0, idx).trim(), line.slice(idx + 1).trim());
  }

  if (fields.get("generator") !== WIKI_GENERATOR_MARKER.slice("generator: ".length)) {
    return { ok: false, reason: "not generated by oh-memos wiki-export", foreign: true };
  }

  const id = fields.get("id") ?? "";
  if (!id) return { ok: false, reason: "front-matter has no id", foreign: false };

  const type = fields.get("type") ?? "";
  if (!TYPE_RE.test(type)) {
    return {
      ok: false,
      reason: `invalid memory type '${type}' (must be ${TYPE_RE} shape)`,
      foreign: false,
    };
  }

  const status = fields.get("status") || "activated";
  if (!["activated", "archived", "deleted"].includes(status)) {
    return { ok: false, reason: `invalid status '${status}'`, foreign: false };
  }
  const tags = parseTags(fields.get("tags") ?? "");
  const confidenceRaw = fields.get("confidence");
  const confidence = confidenceRaw === undefined ? undefined : Number(confidenceRaw);
  if (confidenceRaw !== undefined && (confidence === undefined || !Number.isFinite(confidence) || confidence < 0 || confidence > 1)) {
    return { ok: false, reason: "invalid confidence (must be between 0 and 1)", foreign: false };
  }
  const created = fields.get("created");
  const updated = fields.get("updated");

  const bodyStart = end + 1;
  let cursor = bodyStart;
  while (cursor < lines.length && lines[cursor].trim() === "") cursor++;
  const heading = lines[cursor] ?? "";
  if (!heading.startsWith("# ")) {
    return { ok: false, reason: "missing H1 title after front-matter", foreign: false };
  }
  const title = heading.slice(2).trim();
  cursor++;

  const contentLines: string[] = [];
  const related: string[] = [];
  let inRelated = false;
  for (; cursor < lines.length; cursor++) {
    const line = lines[cursor];
    if (line.trim() === RELATED_HEADING) {
      inRelated = true;
      continue;
    }
    if (inRelated) {
      if (line.trim().startsWith("- ")) related.push(line.trim());
    } else {
      contentLines.push(line);
    }
  }

  while (contentLines.length > 0 && contentLines[contentLines.length - 1].trim() === "") {
    contentLines.pop();
  }
  const content = contentLines.join("\n").trim();
  if (!content) return { ok: false, reason: "empty content (title only)", foreign: false };

  return { ok: true, page: { id, type, status, tags, confidence, created, updated, title, content, related } };
}
