/**
 * memos_export_wiki — render a cube as an interlinked markdown wiki
 *
 * One page per memory + index.md + graph.md, written into the target project
 * (default <project_path>/docs/memory-wiki) so the wiki is human-readable and
 * git-versionable. Data comes from the existing /product/graph/data endpoint
 * (paginated full export); rendering and file IO happen HERE on the client
 * side because the Python API runs on Windows and cannot interpret WSL-style
 * project paths. (Decision record: docs/plans/2026-08-01-memos-think-wiki-export.md)
 *
 * Safety: every generated file carries a marker (frontmatter `generator:` for
 * pages, an HTML comment for index/graph). Re-export deletes ONLY marked
 * files; anything else found in the output tree is left untouched and listed
 * as a warning.
 */

import * as fs from "fs";
import * as path from "path";
import { MEMOS_URL, logger } from "../config.js";
import { fetchWithTimeout } from "../api-client.js";
import { ensureCubeRegistered } from "../cube-manager.js";
import { extractMcpType } from "../query-processing.js";
import { EDGE_LABELS } from "../wiki-relations.js";
import { getTypeIcon } from "../models.js";
import type { TextContent, MemoryNode, GraphEdge } from "../types.js";
import {
  ERR_OPERATION_FAILED,
  ERR_PARAM_MISSING,
  apiErrorResponse,
  cubeRegistrationError,
  errorResponse,
  getCubeIdFromArgs,
} from "./utils.js";

const COMMENT_MARK = "<!-- generated by oh-memos wiki-export -->";
const GENERATOR_FIELD = "generator: oh-memos-wiki-export";
const PAGE_SIZE = 100;
const MAX_PAGES = 10; // hard cap: 1000 nodes per export
const MERMAID_NODE_LIMIT = 80;

// ============================================================================
// Data fetch (paginated /product/graph/data)
// ============================================================================

interface GraphDump {
  nodes: MemoryNode[];
  edges: GraphEdge[];
  totalNodes: number;
  truncated: boolean;
}

async function fetchAllGraphData(cubeId: string): Promise<GraphDump | string> {
  const nodes: MemoryNode[] = [];
  const edges: GraphEdge[] = [];
  let totalNodes = 0;
  let totalEdges = 0;

  for (let page = 1; page <= MAX_PAGES; page++) {
    const response = await fetchWithTimeout(`${MEMOS_URL}/product/graph/data`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      // user_id doubles as the Neo4j user_name filter server-side, and cube
      // data is stored under user_name == cube_id (same as the temporal query).
      body: JSON.stringify({ user_id: cubeId, page, page_size: PAGE_SIZE }),
      timeoutMs: 60,
    });

    if (!response.ok) return `HTTP ${response.status}`;
    const payload = await response.json() as Record<string, unknown>;
    if (payload.code !== 200) return String(payload.message ?? "Unknown error");

    const data = (payload.data ?? {}) as Record<string, unknown>;
    const pageNodes = (data.nodes as MemoryNode[]) ?? [];
    const pageEdges = (data.edges as GraphEdge[]) ?? [];
    totalNodes = Number(data.total_nodes ?? pageNodes.length);
    totalEdges = Number(data.total_edges ?? pageEdges.length);

    nodes.push(...pageNodes);
    edges.push(...pageEdges);

    if (page * PAGE_SIZE >= Math.max(totalNodes, totalEdges)) break;
  }

  return { nodes, edges, totalNodes, truncated: totalNodes > MAX_PAGES * PAGE_SIZE };
}

// ============================================================================
// Rendering helpers
// ============================================================================

interface WikiPage {
  id: string;
  type: string;
  title: string;
  fileBase: string; // without extension
  relPath: string; // pages/<TYPE>/<fileBase>.md
  node: MemoryNode;
  meta: Record<string, unknown>;
}

function nodeMeta(node: MemoryNode): Record<string, unknown> {
  return (node.metadata ?? {}) as Record<string, unknown>;
}

function slugify(s: string): string {
  const slug = s
    .toLowerCase()
    .replace(/[^\p{Script=Han}a-z0-9]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60)
    .replace(/-+$/g, "");
  return slug || "memory";
}

function yamlEscape(s: string): string {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function buildPages(nodes: MemoryNode[]): WikiPage[] {
  const pages: WikiPage[] = [];
  const usedNames = new Set<string>();

  for (const node of nodes) {
    const meta = nodeMeta(node);
    const id = node.id ?? String(meta.id ?? "");
    if (!id) continue;

    const type = extractMcpType(node);
    const text = (node.memory ?? "").replace(/^\[[A-Z_]+\]\s*/, "");
    const key = node.key ?? String(meta.key ?? "");
    const title = (key || text.split("\n")[0] || id).slice(0, 120);
    const date = String(node.created_at ?? meta.created_at ?? node.updated_at ?? meta.updated_at ?? "").slice(0, 10) || "undated";

    let fileBase = `${date}-${slugify(title)}`;
    if (usedNames.has(fileBase)) fileBase = `${fileBase}-${id.slice(0, 8)}`;
    usedNames.add(fileBase);

    pages.push({ id, type, title, fileBase, relPath: `pages/${type}/${fileBase}.md`, node, meta });
  }
  return pages;
}

// Labels live in wiki-relations.ts so export and import cannot drift apart:
// a label changed on only one side would silently stop resolving on re-import.

function renderPage(page: WikiPage, edges: GraphEdge[], byId: Map<string, WikiPage>): string {
  const { node, meta } = page;
  const text = (node.memory ?? "").replace(/^\[[A-Z_]+\]\s*/, "");
  const tags = (node.tags ?? (meta.tags as string[]) ?? []) as string[];
  const created = String(node.created_at ?? meta.created_at ?? "");
  const updated = String(node.updated_at ?? meta.updated_at ?? "");

  const fm: string[] = [
    "---",
    GENERATOR_FIELD,
    `id: ${page.id}`,
    `type: ${page.type}`,
    `status: ${String(meta.status ?? "activated")}`,
  ];
  if (Array.isArray(tags) && tags.length > 0) fm.push(`tags: [${tags.map((t) => yamlEscape(String(t))).join(", ")}]`);
  if (meta.confidence !== undefined && meta.confidence !== null) fm.push(`confidence: ${meta.confidence}`);
  if (created) fm.push(`created: ${created}`);
  if (updated) fm.push(`updated: ${updated}`);
  fm.push("---", "");

  const body: string[] = [`# ${page.title}`, "", text.trim(), ""];

  const related: string[] = [];
  for (const edge of edges) {
    if (!edge.source || !edge.target) continue;
    if (edge.source === page.id && byId.has(edge.target)) {
      const t = byId.get(edge.target)!;
      related.push(`- ${EDGE_LABELS[edge.type ?? ""] ?? edge.type ?? "关联"} → [[${t.fileBase}]]`);
    } else if (edge.target === page.id && byId.has(edge.source)) {
      const s = byId.get(edge.source)!;
      related.push(`- 被${EDGE_LABELS[edge.type ?? ""] ?? edge.type ?? "关联"} ← [[${s.fileBase}]]`);
    }
  }
  if (related.length > 0) {
    body.push("## 关联", "", ...related, "");
  }

  return [...fm, ...body].join("\n");
}

function renderIndex(cubeId: string, pages: WikiPage[], edgeCount: number, warnings: string[]): string {
  const byType = new Map<string, WikiPage[]>();
  for (const p of pages) {
    if (!byType.has(p.type)) byType.set(p.type, []);
    byType.get(p.type)!.push(p);
  }

  const lines: string[] = [
    COMMENT_MARK,
    `# Memory Wiki — ${cubeId}`,
    "",
    `> 由 oh-memos 导出 · ${new Date().toISOString()} · ${pages.length} 页 · ${edgeCount} 条关联`,
    `> 可编辑镜像:修改生成页后用 \`memos_import_wiki\` 回灌(未改动的页自动跳过);重导出会覆盖本地改动。`,
    "",
  ];

  for (const [type, typePages] of [...byType.entries()].sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`## ${getTypeIcon(type)} ${type} (${typePages.length})`, "");
    const sorted = [...typePages].sort((a, b) => b.fileBase.localeCompare(a.fileBase));
    for (const p of sorted) {
      lines.push(`- [${p.title}](${p.relPath}) · ${p.fileBase.slice(0, 10)}`);
    }
    lines.push("");
  }

  if (warnings.length > 0) {
    lines.push("## ⚠️ 导出警告", "", ...warnings.map((w) => `- ${w}`), "");
  }
  lines.push("", "[图谱总览](graph.md)");
  return lines.join("\n");
}

function mermaidLabel(p: WikiPage): string {
  return p.title.slice(0, 30).replace(/["[\]{}()<>|]/g, " ");
}

function renderGraphOverview(pages: WikiPage[], edges: GraphEdge[], byId: Map<string, WikiPage>): string {
  const lines: string[] = [COMMENT_MARK, "# 图谱总览", ""];

  if (pages.length > MERMAID_NODE_LIMIT) {
    lines.push(`*节点数 ${pages.length} 超过 ${MERMAID_NODE_LIMIT},跳过 mermaid 渲染(参见 index.md)。*`);
    return lines.join("\n");
  }

  const connected = new Set<string>();
  const edgeLines: string[] = [];
  for (const edge of edges) {
    if (!edge.source || !edge.target || !byId.has(edge.source) || !byId.has(edge.target)) continue;
    const s = byId.get(edge.source)!;
    const t = byId.get(edge.target)!;
    connected.add(s.id);
    connected.add(t.id);
    const arrow = edge.type === "CONFLICT" ? `== ${edge.type} ==>` : `-- ${edge.type ?? "RELATE"} -->`;
    edgeLines.push(`    n${s.id.slice(0, 8)}["${mermaidLabel(s)}"] ${arrow} n${t.id.slice(0, 8)}["${mermaidLabel(t)}"]`);
  }

  lines.push("```mermaid", "graph LR");
  lines.push(...edgeLines);
  const orphans = pages.filter((p) => !connected.has(p.id));
  for (const p of orphans.slice(0, 20)) {
    lines.push(`    n${p.id.slice(0, 8)}["${mermaidLabel(p)}"]`);
  }
  lines.push("```", "");
  if (orphans.length > 20) lines.push(`*另有 ${orphans.length - 20} 个孤立节点未画出。*`);
  return lines.join("\n");
}

// ============================================================================
// File IO (marker-guarded)
// ============================================================================

function isGeneratedFile(filePath: string): boolean {
  try {
    const head = fs.readFileSync(filePath, "utf8").slice(0, 500);
    return head.includes(GENERATOR_FIELD) || head.includes(COMMENT_MARK);
  } catch {
    return false;
  }
}

/** Delete previously generated .md files under dir; return foreign files kept. */
function cleanGenerated(dir: string): string[] {
  const foreign: string[] = [];
  if (!fs.existsSync(dir)) return foreign;

  const walk = (d: string): void => {
    for (const entry of fs.readdirSync(d, { withFileTypes: true })) {
      const full = path.join(d, entry.name);
      if (entry.isDirectory()) {
        walk(full);
        try {
          if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
        } catch { /* keep */ }
      } else if (entry.name.startsWith(".")) {
        continue; // tool-owned state (.wiki-import-ledger.json), not user content
      } else if (entry.name.endsWith(".md")) {
        if (isGeneratedFile(full)) fs.unlinkSync(full);
        else foreign.push(path.relative(dir, full));
      } else {
        foreign.push(path.relative(dir, full));
      }
    }
  };
  walk(dir);
  return foreign;
}

// ============================================================================
// Handler
// ============================================================================

export async function handleMemosExportWiki(arguments_: Record<string, unknown>): Promise<TextContent[]> {
  const cubeId = getCubeIdFromArgs(arguments_);
  const projectPath = arguments_.project_path as string | undefined;
  const includeArchived = arguments_.include_archived === true;

  const outputDir = (arguments_.output_dir as string | undefined)
    ?? (projectPath ? path.join(projectPath, "docs", "memory-wiki") : undefined);
  if (!outputDir) {
    return errorResponse(
      "Need project_path (default output: <project_path>/docs/memory-wiki) or an explicit output_dir",
      ERR_PARAM_MISSING,
      ['`memos_export_wiki(project_path="/mnt/g/my/project")`', '`memos_export_wiki(cube_id="x", output_dir="/tmp/wiki")`']
    );
  }
  const resolvedOut = path.resolve(outputDir);

  const [regSuccess, regError] = await ensureCubeRegistered(cubeId);
  if (!regSuccess) return cubeRegistrationError(cubeId, regError);

  const dump = await fetchAllGraphData(cubeId);
  if (typeof dump === "string") return apiErrorResponse("Wiki export (graph data)", dump);

  // Filter: drop scheduler-managed WorkingMemory nodes and (by default) any
  // non-activated memory. The hierarchy field (WorkingMemory/LongTermMemory/
  // UserMemory) is a different axis from the MCP business type stored in tags.
  const exportable = dump.nodes.filter((node) => {
    const meta = nodeMeta(node);
    if (String(meta.memory_type ?? "") === "WorkingMemory") return false;
    const status = String(meta.status ?? "activated");
    if (status === "deleted") return false;
    if (!includeArchived && status !== "activated") return false;
    return true;
  });

  if (exportable.length === 0) {
    return errorResponse(`Cube '${cubeId}' has no exportable memories`, ERR_OPERATION_FAILED, [
      'Check the cube has activated memories: `memos_admin(action="stats")`',
      "Archived-only cube? Retry with include_archived=true",
    ]);
  }

  const pages = buildPages(exportable);
  const byId = new Map(pages.map((p) => [p.id, p]));
  const innerEdges = dump.edges.filter((e) => e.source && e.target && byId.has(e.source) && byId.has(e.target));

  try {
    fs.mkdirSync(resolvedOut, { recursive: true });
    const foreign = cleanGenerated(resolvedOut);

    for (const page of pages) {
      const abs = path.join(resolvedOut, page.relPath);
      fs.mkdirSync(path.dirname(abs), { recursive: true });
      fs.writeFileSync(abs, renderPage(page, innerEdges, byId), "utf8");
    }

    const warnings: string[] = [];
    if (dump.truncated) warnings.push(`cube 共 ${dump.totalNodes} 节点,超过导出上限 ${MAX_PAGES * PAGE_SIZE},仅导出最新部分`);
    if (foreign.length > 0) warnings.push(`目录中有 ${foreign.length} 个非生成文件未动: ${foreign.slice(0, 5).join(", ")}${foreign.length > 5 ? " …" : ""}`);

    fs.writeFileSync(path.join(resolvedOut, "index.md"), renderIndex(cubeId, pages, innerEdges.length, warnings), "utf8");
    fs.writeFileSync(path.join(resolvedOut, "graph.md"), renderGraphOverview(pages, innerEdges, byId), "utf8");

    logger.info(`Wiki export: ${pages.length} pages -> ${resolvedOut}`);

    const typeCounts = new Map<string, number>();
    for (const p of pages) typeCounts.set(p.type, (typeCounts.get(p.type) ?? 0) + 1);

    const lines = [
      `## 📖 Wiki 导出完成`,
      "",
      `**输出**: \`${resolvedOut}\``,
      `**页面**: ${pages.length}(${[...typeCounts.entries()].sort((a, b) => b[1] - a[1]).map(([t, c]) => `${t}×${c}`).join(", ")})`,
      `**关联**: ${innerEdges.length} 条 wikilink · 入口 \`index.md\``,
      "",
      ...(warnings.length > 0 ? ["⚠️ " + warnings.join(";"), ""] : []),
      "💡 建议将该目录纳入 git 版本管理(`git add docs/memory-wiki`)以获得记忆的版本史。",
    ];
    return [{ type: "text", text: lines.join("\n") }];
  } catch (err) {
    return errorResponse(`Wiki export failed: ${err}`, ERR_OPERATION_FAILED, [
      `Check the output directory is writable: ${resolvedOut}`,
    ]);
  }
}
