# Generates docker/.env.migration from the live src/.env.
#
# Why this exists: the Windows config is already correct and battle-tested, but
# a container cannot use it verbatim — `localhost` inside a container is the
# container itself, so the LLM relay on :3000 and any other host-only endpoint
# would be unreachable. This copies every value over and rewrites only what has
# to change, so the two sides stay behaviourally identical.
#
# Database addresses are deliberately NOT copied: compose sets those to the
# service names (or host.docker.internal in host-db mode).

$ErrorActionPreference = 'Stop'

$repo = (Get-Item "$PSScriptRoot\..\..").FullName
$src  = Join-Path $repo 'src\.env'
$out  = Join-Path $repo 'docker\.env.migration'

if (-not (Test-Path $src)) { throw "src/.env not found at $src" }

# Keys compose owns, or that are meaningless / harmful inside the container.
$drop = @(
    'MEMOS_URL', 'MEMOS_CUBES_DIR', 'MOS_CUBE_PATH', 'MEMOS_BASE_PATH',
    'NEO4J_URI', 'NEO4J_HTTP_URL', 'QDRANT_HOST', 'QDRANT_PORT',
    'MEMOS_AUTO_ARCHIVE', 'MOS_ENABLE_REORGANIZE', 'MEMOS_STARTUP_CUBES'
)

$inherited = New-Object System.Collections.Generic.List[string]
foreach ($line in [System.IO.File]::ReadAllLines($src)) {
    if ($line -notmatch '^[A-Za-z_][A-Za-z0-9_]*=') { continue }
    $parts = $line -split '=', 2
    $key   = $parts[0]
    if ($drop -contains $key) { continue }

    # Drop inline comments: several are mojibake in this repo, and a corrupted
    # comment must never end up inside a value.
    $val = ($parts[1] -split '\s+#')[0].TrimEnd()

    # Host-only endpoints have to go through the gateway alias to be reachable.
    $val = $val -replace '://localhost:', '://host.docker.internal:'
    $val = $val -replace '://127\.0\.0\.1:', '://host.docker.internal:'

    $inherited.Add("$key=$val")
}

$header = @(
    '# Generated by scripts/migrate/build_migration_env.ps1 from src/.env.',
    '# Do not edit by hand: re-run the generator instead.',
    '#',
    '# localhost endpoints were rewritten to host.docker.internal so they resolve',
    '# from inside the container. Database addresses come from compose.',
    '',
    'OH_MEMOS_DOCKER_ENV_FILE=./.env.migration',
    'MEMOS_CUBES_HOST_DIR=D:/oh-memos-data/cubes',
    'OH_MEMOS_MIGRATION_DIR=D:/oh-memos-migration',
    '',
    'MEMOS_IMAGE=oh-memos',
    'MEMOS_TAG=migration',
    'MEMOS_BIND_ADDRESS=127.0.0.1',
    'MEMOS_HOST_PORT=18100',
    'NEO4J_HTTP_HOST_PORT=17474',
    'NEO4J_BOLT_HOST_PORT=17687',
    'QDRANT_HTTP_HOST_PORT=16399',
    'QDRANT_GRPC_HOST_PORT=16434',
    '',
    '# Background writers stay off during migration so archive/reorganize cannot',
    '# rewrite the freshly imported graph while counts are being reconciled.',
    'MEMOS_AUTO_ARCHIVE=false',
    'MOS_ENABLE_REORGANIZE=false',
    'MEMOS_STARTUP_CUBES=',
    '',
    '# --- inherited from src/.env ---'
)

[System.IO.File]::WriteAllLines($out, ($header + $inherited))
Write-Host "Wrote $out"
Write-Host "  inherited keys: $($inherited.Count)"
Write-Host "  rewritten to host.docker.internal:"
$inherited | Where-Object { $_ -match 'host\.docker\.internal' } | ForEach-Object {
    Write-Host ('    ' + (($_ -split '=', 2)[0]))
}
